# Generated by Django 2.2.5 on 2019-09-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TakadApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='users',
            name='salt',
        ),
    ]
