# Generated by Django 2.2.5 on 2019-09-25 11:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TakadApp', '0005_reports_result_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports_result',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 14, 10, 34, 168679)),
        ),
        migrations.AlterField(
            model_name='reports_result',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TakadApp.Users'),
        ),
    ]
