# Generated by Django 2.2.5 on 2019-09-25 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TakadApp', '0011_auto_20190925_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports_result',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 16, 57, 40, 874792)),
        ),
    ]
