# Generated by Django 2.2.5 on 2019-09-25 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TakadApp', '0015_auto_20190925_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports_result2',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 17, 2, 20, 5836)),
        ),
    ]
