# Generated by Django 2.2.5 on 2019-09-25 14:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TakadApp', '0017_auto_20190925_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_scan', models.TextField()),
                ('is_file', models.BooleanField(default=False)),
                ('dict_report', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 9, 25, 17, 3, 30, 179013))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TakadApp.Users')),
            ],
        ),
        migrations.DeleteModel(
            name='Reports_result2',
        ),
    ]
