# Generated by Django 2.2.5 on 2019-09-25 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TakadApp', '0018_auto_20190925_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports_result',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 17, 5, 58, 612089)),
        ),
    ]
