# Generated by Django 2.2.5 on 2019-09-25 14:06

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TakadApp', '0019_auto_20190925_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports_result',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 17, 6, 44, 144116)),
        ),
        migrations.AlterField(
            model_name='reports_result',
            name='dict_report',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
