# Generated by Django 2.2.5 on 2019-09-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TakadApp', '0023_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='replay',
            field=models.TextField(default=''),
        ),
    ]
