# Generated by Django 2.2.5 on 2019-09-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TakadApp', '0026_auto_20190927_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports_result',
            name='sacnName',
            field=models.BooleanField(default=False),
        ),
    ]
