# Generated by Django 2.2.5 on 2019-09-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TakadApp', '0027_auto_20190927_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports_result',
            name='sacnName',
            field=models.TextField(default=''),
        ),
    ]
